"""empty message

Revision ID: 56de3ba9ce62
Revises: f841d94b0f37
Create Date: 2025-08-07 02:41:36.300917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56de3ba9ce62'
down_revision = 'f841d94b0f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
