"""empty message

Revision ID: f0876b42e02d
Revises: 9a993dbc0886
Create Date: 2025-08-11 17:34:38.449384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0876b42e02d'
down_revision = '9a993dbc0886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], )
    )
    op.drop_table('Follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='Follower_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='Follower_user_to_id_fkey')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###
